### ISSUE TITLE
Trying to make this work: can't load metaweblog

### ISSUE THREAD

**Issue by joshkerr** [tominsam/jekyll-metaweblog#1]
I'm trying to get this to work but stuck at this error:

 /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- metaweblog (LoadError)
    from /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from ./jm_server.rb:6:in `<main>'

Am I missing a gem?  Is there more to the setup other than the instructions that you provided?

**Comment by tominsam** [comment]
Are you running jm_server from the directory you cloned the source into? It looks like there's not a metaweblog.rb in the current directory, but it's definitely. in the checkout.

**Comment by joshkerr** [comment]
I ended up having to include the files this way:

require File.join(File.dirname(**FILE**), 'post')

Not sure why.  Got it working.  

## 

Josh Kerr
