### ISSUE TITLE
Windows live writer does not work with this

### ISSUE THREAD

**Issue by joshkerr** [tominsam/jekyll-metaweblog#3]
Generates an error message and won't allow you to setup a connection.  Not really expecting support for it, but it would be nice if you could.

**Comment by tominsam** [comment]
Very hard to do anything about this without more information, as I have neither windows live writer, nor a windows box to run it on :)

**Comment by joshkerr** [comment]
Invalid server response.  The response to the blogger.getUserBlogs method received from the blog server was invalid.  

Object reference not set to an instance of an object.

I know, not very helpful.

**Comment by tominsam** [comment]
getUsersBlogs has 2 different implementations depending on if it's called as blogger.getUsersBlogs or wp.getUsersBlogs. But I _try_ to return something that works in both cases.

metaweblog is a pain - there's no central spec, and noone sticks to what little spec there is anyway. To fix this I'd need to know what sort of response live writer is expecting, then change my code to return the right thing. Can you send me the log file (Help | About | Show log file apparently) 

Alternatively, can you manually specify the blog ID anywhere in the UI? That should bypass the call to getUsersBlogs and make things work. Or it might just move you along to the next error message...

**Comment by tominsam** [comment]
Hmm, I think I missed a spelling difference between the APIs. I've pushed a change to the blogger.getUserBlogs api - can you also pull and try that? Thanks.

**Comment by joshkerr** [comment]
That update fixed the issue.  Windows Live Writer now works.  Thanks.
